server:
  port: 8082

management:
   security:
    enabled: false

endpoints:
  metrics:
    sensitive: false
  trace:
      sensitive: false



spring:
  profiles:
#    active: rpi
  thymeleaf:
    cache: false